#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello_page:
      path: /home
      controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
      defaults:
          templates: 'hello_page.html.twig'
